language: node_js
node_js:
  - 13

  deploy:
    provider: s3
    access_key_id: AKIARE5CPEVRCZNVCWA2
    secret_access_key: pWzb5vohrT92VePGDdWbpw2bDJgTRiMVuwGG4mW1j6rWsbI5RhOH0ZpaaioTdecRduH7AJ15MDwdQVkkdwLfE42s2rlNdXOa088/ohn3dTelSeOl5qDM9IR7pbyUgeKX/8HtddSnDeRGx3pHsHszO2KpARDE7VRJPwkoyIrbQLiL9mX8RrIKZwoJIY7f35bVXYPRQ1bvr90OKO29FlqfBcMxsNEc/Feri5JvW9Bx2jl4aY325d9Jnvib4qq/tCUGqWn4BT6HGYlilruqaqjCWIuuSyaIFxH3NDWKyop5m9E7cUkMeTJW9wellmfOloElQb4gPQ9lSnFKtriC2qWOwGXovBcXocnUf9i5tTxCWq8g1k/qC5cZynQehXuyRf7zBbmXnzSmL/XytdrR7gexk6E1Fd6U0xzPLFdX1n9ZrW2utpBlzEMwJY+cbhZStIkcTCAlGptdB/tuF8CGcbazZPenzZAZWphPM3G+W+WRx6Ja8UyWlGfH6x3+QcaYZuhhWnYhhey5pBrQIxPILzEHB1ABECgO3ru2mfyErcGgwAFJzH10vzx+4j03E2H66r6bdzH7jRq8YebGDGcLJHo6JnXJJSKocfjquyXW7+jltlmX8ykcreUE/vj7J8uMA1yhncwJ0LTwzYpEuyn21Ep+5yT8z1Qh/kB8kYtnyGkvPDY=
    bucket: travis-reports-ml
    skip_cleanup: true
    local_dir: mochawesome-report
    upload-dir: mocha-reports
    region: eu-north-1